weights: yolov7x.pt
cfg: OT/OT_yolov7x/OT_yolov7x.yaml
data: OT/OT_yolov7x/OT_data.yaml
hyp: data/hyp.scratch.p5.yaml
epochs: 300
batch_size: 4
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: yolov7x
entity: yolov7x
name: OT_yolov7x
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
world_size: 1
global_rank: -1
save_dir: yolov7x/OT_yolov7x
total_batch_size: 4
